# Site settings
title: Koen van Zuijlen
description: > # this means to ignore newlines until "baseurl:"
  Personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

sass:
  style: compressed

gems:
  - jekyll-timeago

jekyll_timeago:
  depth: 1
  suffix: ''
  years: ''
  year: ''